version: '3'
services:
    client:
        stdin_open: true # docker run -i. Interactive mode (-it) to avoid react-scripits from exiting 
        tty: true        # docker run -t. Interactive mode (-it) to avoid react-scripits from exiting
        build:  
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        links:
            - api
        volumes: 
            - './usr/src/app'
    api:   
        build:
            context: .
            dockerfile: Dockerfile  
        ports:
            - "5000:5000"